language: python
cache: pip
python:
- 3.6
install:
- pip install -r requirements.txt
- pip install -r requirements-dev.txt
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build
script:
- coverage run -m unittest discover -t tests --verbose
after_script:
- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
after_success:
- bash <(curl -s https://codecov.io/bash)
env:
  global:
  - INGEST_API="http://api.ingest.dev.data.humancellatlas.org/"
  - CC_TEST_REPORTER_ID=8d9c71c325829991c0906c33b0fff1a85d12399c5a0baadfef96dbaeb7f38348
  - secure: Qs5jErRTTk/E6zzJ/bHzXeGDg6jGWQcT8GbgFuhBarexEW/cvsJcVP+10zvu8hMAyIi0nxK5C6P7GGp8ATUmDzYfkCx6MN+G1dYpuWhuFJEonh9TnbC6ZKOyRhVOzIeCoV74uTw09c6OlGQQP7MJwnW3fZT+SEEI/jKgOgu6pG87zYV62tQUFXQgYaf3mTJ0uP5+/EvvRWZcRN5TsFGfnfW4ZMiZlCzmaU5o00H2LK7wO1pCQp5998dkWMqFviGgcxiEyGoJ/Zkl36Pm/l0tQZpZUp/9NvytdGswoiEFLGB7tdjeeqao94TWDmMEGLQZzvaU0KtxOx5ibdpOiEztDdASSu6Fnp73kvIphlsfK79H3QU2tEzErHUUVF3bVLAFZt9hbvl81qwrXrlFW85owhXOsjKpzIASRCy1/o7tx5+s8UPORTx4fNb4/PURxPKJpAwompHjepI022DAG/rs+fJI25rSx/FwouZI16g0zd90fdGkYm+vAxLI0nLqUK9jiXfKUTgn+TxKK7KPMSed9wqbkqujBStFMVs416l3Exhx3+LFhuiuWCKeXt9OkzwR3eav96MPmzHR6I8P+P2VCZ0qsLMAzCFlEDGPgSEngtv0GnoW4exQQw++sxImCS4dfAJ1YeCk3w2sPozYNfgqYGtJuyUQpu4Px9bkXhGTDSQ=
notifications:
  slack: humancellatlas:efniDWHvhyZeSZCqOeWTqo5K
